all:
    vars:
        ansible_user: centos
        ansible_connection: ssh
        ansible_ssh_user: centos
        ansible_ssh_pass: *****
    children:
        reachengine_environment:
            children:
                xsd-host:
                    hosts:
                        10.0.0.4:
                runtime:
                    hosts:
                        10.0.0.5:
                        10.0.0.6:
                webapp:
                    hosts:
                        10.0.0.2:
